# Generated by Django 5.2.7 on 2025-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='myapp.student'),
        ),
    ]
