# Generated by Django 5.2.7 on 2025-10-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_approved',
        ),
    ]
